---
# ansible-playbook main.yml
- name: Run plebis on remote server
  hosts: host2
  sudo: True
  tasks:
    - name: Create data directory
      file: >
          name=/var/lib/plebis
          state=directory
          owner=www-data
          group=www-data
          mode=755
    - name: Stop plebis container
      docker: name=plebis image=localhost:5000/plebis state=stopped
    - name: Remove plebis container
      command: docker rm plebis
    - name: Start plebis container
      command: docker run --name=plebis -d --restart=always -v /var/lib/plebis:/opt/plebis/data localhost:5000/plebis
